modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Arborsm/GT--/issues"
license = "MIT"

[[mods]]
modId = "gtnn"
version = "${version}"
displayName = "GT--"
authors = "${mod_authors}"
description = '''${mod_description}'''
#logoFile = ""

[[dependencies.gtnn]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "gtceu"
mandatory = true
versionRange = "[1.4.1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "ad_astra"
mandatory = false
versionRange = "[1.15.18,)"
ordering = "AFTER"
side = "BOTH"