modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Arborsm/GT--/issues"
license = "MIT"

[[mods]]
modId = "addon"
version = "${version}"
displayName = "addon"
authors = "${mod_authors}"
description = '''${mod_description}'''
#logoFile = ""

[[dependencies.addon]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.addon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.addon]]
modId = "gtceu"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"