modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "gtnn"
version = "${version}"
displayName = "GT--"
authors = "Arborsm"
description = '''${mod_description}'''
#logoFile = ""

[[dependencies.gtnn]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "gtceu"
mandatory = true
versionRange = "[1.0.14.a,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gtnn]]
modId = "ad_astra"
mandatory = false
versionRange = "[1.15.4,)"
ordering = "AFTER"
side = "BOTH"