modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "gtnn"
version = "${mod_version}"
displayName = "GT--"
authors = "Arborsm"
description = '''${mod_description}'''
#logoFile = ""

[[dependencies.gtnn]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "gtceu"
mandatory = true
versionRange = "[1.1.3.b,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gtnn]]
modId = "ad_astra"
mandatory = false
versionRange = "[1.15.10,)"
ordering = "AFTER"
side = "BOTH"