# Make sure this is set to "kotlinforforge"
modLoader = "kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Arborsm/GT--/issues"
license = "MIT"

[[mods]]
modId = "gtnn"
version = "${version}"
displayName = "GT--"
authors = "${mod_authors}"
description = '''${mod_description}'''
#logoFile = ""

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.gtnn]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0-alpha,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtnn]]
modId = "gtceu"
type = "required"
versionRange = "[1.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gtnn]]
modId = "ad_astra"
type = "optional"
versionRange = "[1.15.10,)"
ordering = "AFTER"
side = "BOTH"